version: '2' 
services: 
  nginx: 
    image: nginx:latest 
    ports: 
      - "83:83"
    volumes: 
      - ./nginx:/nginx.conf.d
      - ./static:/staticfiles # web의 static 경로와 마운팅
    depends_on:
      - web
  
  mysql:
    container_name: mysql
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      MYSQL_DATABASE: todolist_database
      MYSQL_ROOT_PASSWORD: ${DJANGO_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "3309:3309"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./static:/code/static/files/staticfiles # code로 생성 후 마운팅
    expose:
      - "8083"
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - mysql
    links:
      - mysql:mysql
    restart: always