# Generated by Django 4.1.7 on 2023-03-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='todo_complete_count',
            field=models.BigIntegerField(default=0, null=True, verbose_name='TODO_COMPLETE_COUNT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='todo_count',
            field=models.BigIntegerField(default=0, null=True, verbose_name='TODO_COUNT'),
        ),
    ]
