# Generated by Django 4.1.7 on 2023-03-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_todo_complete_count_alter_user_todo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('S', 'SILVER'), ('G', 'GOLD'), ('P', 'PLATINUM'), ('D', 'DIAMOND'), ('M', 'MASTER')], default='S', max_length=10, null=True, verbose_name='RANK'),
        ),
    ]
