# Generated by Django 4.1.7 on 2023-03-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_social_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.BooleanField(default=False, verbose_name='SOCIAL'),
        ),
    ]
