# Generated by Django 4.1.7 on 2023-03-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_writer_todo_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('created_at',), 'verbose_name': 'todo', 'verbose_name_plural': 'todos'},
        ),
    ]
