# Generated by Django 4.1.7 on 2023-03-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-created_at',), 'verbose_name': 'todo', 'verbose_name_plural': 'todos'},
        ),
    ]
