# Generated by Django 4.1.7 on 2023-03-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_created_at_alter_todo_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='TITLE'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=500, verbose_name='DESCRIPTION'),
        ),
    ]
