# Generated by Django 4.1.7 on 2023-03-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todo_title_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20, verbose_name='TITLE'),
        ),
    ]
