# Generated by Django 4.1.7 on 2023-03-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
