# Generated by Django 4.1.7 on 2023-03-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_remove_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='TITLE'),
        ),
    ]
