# Generated by Django 4.1.7 on 2023-03-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='DESCRIPTION'),
        ),
    ]
