# Generated by Django 4.1.7 on 2023-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(error_messages={'max_length': '최대 길이 (500자) 를 초과하였습니다'}, max_length=500, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(error_messages={'max_length': '최대 길이 (20자) 를 초과하였습니다'}, max_length=20, null=True, verbose_name='TITLE'),
        ),
    ]
