# Generated by Django 4.1.7 on 2023-03-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_alter_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=14, null=True, verbose_name='TITLE'),
        ),
    ]
